# Custom Language File for Launcher Customizer

[ejs.app]
title = "Metaverse Launcher"

[ejs.landing]
mediaGitHubURL = "https://github.com/LaeDev/MetaverseLauncher"
mediaTwitterURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "#"

[ejs.settings]
sourceGithubLink = "https://github.com/LaeDev/MetaverseLauncher"
supportLink = "https://github.com/LaeDev/MetaverseLauncher/issues"

[ejs.overlay]
changedLanguageHeader = "You changed the previous language"
